//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sm10.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {
        public string NombreProducto { get; set; }
        public Nullable<int> IdProveedor { get; set; }
        public Nullable<int> IdCategoria { get; set; }
        public string umedida { get; set; }
        public decimal PrecioUnidad { get; set; }
        public short UnidadesEnExistencia { get; set; }
        public int IdProducto { get; set; }
    
        public virtual CATEGORIA CATEGORIA { get; set; }
        public virtual PROVEEDOR PROVEEDOR { get; set; }
    }
}
